# Generated by Django 5.2.3 on 2025-06-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_done', 'date']},
        ),
    ]
